r"""gsasm/rez/gen.py — M7/R5: evaluate resource bodies against type templates.

Turns packet R4's AST (`gsasm/rez/parser.py`) into the exact data bytes each
resource statement produces, computes the 16-bit attribute word from a
resource's attribute-keyword list, and synthesizes the one resource RezIIgs
auto-generates with no source statement at all: `rResName` ($8014, id
`0x00018001`), built from the `"name"` strings attached to other resources.

Everything here was settled by golden-diffing generated bytes against
`work/rezcheck.py`'s parsed `Sys.Resources` fork (see `work/rezgencheck.py`
for the corpus-driven acceptance check, and this module's function
docstrings for the specific byte evidence). Nothing below is guessed from
the general Rez language: every basetype/field-kind this module actually
*emits bytes differently for* was confirmed present in the two corpus files
per the R4 parser's own scoping discipline; constructs the corpus never
exercises (bitstring-valued defaults with no resource value, `align`,
`boolean`, `$$ArrayIndex`/`Subscript`, `wstring`/`cstring`) are implemented
on a best-effort basis for forward-compatibility/hand-tests only and are
flagged as such below.

Public API
==========
    generate(statements) -> list[GenEntry]

    `statements` is exactly what `gsasm.rez.parser.parse()` returns: a flat,
    source-ordered `list[TypeDecl | ResourceStmt | ReadStmt]`.

    Returns a list of `GenEntry` — one entry per `ResourceStmt`/`ReadStmt`
    in `statements`, **in that same source order**, PLUS one extra entry
    appended at the very end for the synthesized `rResName` resource (see
    "rResName synthesis and placement" below for why it goes last).
    `TypeDecl` statements are consulted for their field templates but never
    produce an entry of their own.

    Each `GenEntry` is:
        kind    'resource' | 'read' | 'resname'
        file, line   provenance (from the source statement; '<synthesized>'/0
                     for the resname entry)
        rtype   int  — the resource type (post-macro-expansion numeric id)
        rid     int  — the resource id
        attr    int  — the 16-bit attribute word (see "Attribute word" below)
        name    Optional[bytes] — the resource's own "name" header argument,
                if it had one (only ever set on 'resource' entries in this
                corpus; carried through for completeness)
        data    Optional[bytes] — the fully generated resource data, for
                kind='resource'/'resname'. **None** for kind='read': this
                packet does not implement `read`+Convert (that is the
                concurrently-developed R6 packet's job); the entry is a
                placeholder that preserves the read statement's exact
                *position* in the source-ordered list, its resolved
                (rtype, rid) key, and its already-computed attribute word
                (attribute-word computation is generic across resource/read
                statements and is not exclusive to non-read resources, so
                R5 does it once for everything here rather than punting the
                whole thing to R6).

    R7 (the final CLI/integration packet) is expected to:
      1. Call `generate(statements)`.
      2. For every entry with `kind == 'read'`, obtain the Convert-
         transformed bytes for `(entry.rtype, entry.rid)` from the R6
         packet (`gsasm/rez/convert.py` + whatever `.Load`-file build step
         it wires up) and place them in a `{(rtype, rid): bytes}` mapping.
      3. Call `to_emit_tuples(entries, that_mapping)` to get the final
         `list[(rtype, rid, attr, data)]`, already in the right order for
         `gsasm.rez.emit.emit_fork` (source order, with the synthesized
         rResName last — exactly matching the golden fork's observed data
         layout; see below).

rResName synthesis and placement
=================================
RezIIgs auto-generates one resource with no corresponding source statement:
type $8014 (`rResName`), id `0x00018001`, built from the `"name"` strings
attached to other resources via a `resource TYPE(id, "name", ...)` header's
optional second argument. `work/rezparsecheck.py` already established this
(138 `resource` + 4 `read` statements = 142 explicit statements, one short
of the golden fork's 143 total resources) and TypesIIGS.r's own template:

    type rResName {
        _mybase_ integer;              /* name holder format */
        longint = $$Countof(NAMES);     /* name count */
        array NAMES {
            hex longint;                /* ID of the resource */
            pstring;                    /* Name of the resource */
        };
    };

Golden-diffed directly (`rezcheck.golden_fork(...).resource(0x8014,
0x00018001)`, 59 bytes): `01 00` (format=1, a constant — always observed as
1, never computed from anything) `05 00 00 00` (count=5, little-endian)
then 5 `(id: longint LE, name: pstring)` entries in this exact order:
`(0x07ff0002,"Stop") (0x07ff0003,"Note") (0x07ff0004,"Caution")
(0x07ff0005,"Disk") (0x07ff0006,"Disk Swap")` — precisely the 5
`resource rIcon(id,"name",...)` statements in `sys.resources.r`, **in their
source order** (which happens to also be increasing-id order here, but the
ordering that matters and is reproduced is source order, matching every
other array in this format).

Placement: `rezcheck.py --dump`'s offset-sorted listing of the golden fork
shows rResName's data at the very end of the data region (index 142 of 143,
i.e. dead last — after even the 4 `read`-statement resources, which
otherwise sit early per their early source position). So `generate()`
always appends the resname `GenEntry` last, regardless of where any
individual named resource appeared in `statements`.

Type redeclaration (rCursor / rMyCursor, both template $8027)
==============================================================
`generate()` builds its `typeid -> TypeDecl` lookup table by iterating
`statements` in order and overwriting on each `TypeDecl`, so the *last*
declaration for a given numeric typeid wins — here, sys.resources.r's local
`type rMyCursor { ... }` (declared after `#include "typesiigs.r"`, so
strictly after TypesIIGS.r's `type rCursor { ... }`) wins over TypesIIGS.r's
own $8027 template, matching the design doc's "-rd suppresses redeclaration
warnings" gotcha and its guess that the most-recent declaration wins. This
matters in principle but is a non-issue in practice for this corpus: every
resource statement that instantiates $8027 does so via the `rMyCursor`
identifier (post-macro-expansion, still just the number $8027) and appears
textually after the redeclaration, and the two templates are byte-identical
in every field that affects generation (rMyCursor drops a few cosmetic
`hex` modifiers and comments; `hex` never affects the bytes this module
produces — see "modifiers are generation no-ops" below).

Endianness, pstrings, bitstrings — settled by golden diffing
==============================================================
- **All multi-byte integers (`integer`/`word` 16-bit, `longint` 32-bit,
  and each 16-bit component of `point`/`rect`) are little-endian**,
  confirmed against rWindColor's `0b...` binary literals (e.g. source
  value `0b0000111100000000` = 0x0F00 appears in the golden fork as bytes
  `00 0f`) and rMenu's longint IDs (`$07ff1000` appears as bytes
  `00 10 ff 07`). This holds *inside* resource data; it does not
  contradict the fork header/memo's own big-endian fields (`emit.py`'s
  concern, not this module's).
- **`pstring` is a 1-byte length prefix + raw bytes**, confirmed against
  rVersion(1)'s two pstrings (`\x0fSystem Software`, length byte 0x0f=15
  matching the 15-character string) and cross-checked against the total
  resource size.
- **`string`/hex-`string` fields are raw bytes with NO length prefix and NO
  implicit terminator** — confirmed against rErrorString resources (e.g.
  `"53/No error occurred ($0)./^#0\0x00"` produces exactly
  `b'53/No error occurred ($0)./^#0\x00'`, 31 bytes — the trailing NUL
  comes only from the explicit `\0x00` escape, not from the field type).
  A field's `[size-expr]` bracket (e.g. rCursor/rMyCursor's
  `hex string[2*$$Word(height)*$$Word(width)]`, rIcon's
  `hex string [$$Word(image)]`) is **never evaluated for generation** —
  the actual byte count is simply `len()` of the literal `StrLit`/`HexLit`
  value the resource statement supplies. (Real Rez needs the bracket
  expression to know how many bytes to *read* on the DeRez/parse-back
  direction; going the compile direction, source already hands us the
  exact bytes, so the bracket is redundant information we don't need to
  trust or recompute.)
- **`char` is exactly 1 byte.** rMenuItem's `char;` fields, given `""`
  (empty `StrLit`) in every corpus occurrence, produce a single `0x00`
  byte (confirmed against golden `rMenuItem` bytes) — i.e. a `char` field
  takes its string value's first byte, or 0 if the string is empty.
- **`bitstring[N]` fields pack MSB-first (most-significant bit of the
  *declared* field is the high bit)** within their enclosing byte(s),
  confirmed via rVersion's `ReverseBytes` group: `hex bitstring[4]` Minor=0
  then `hex bitstring[4]` Bug=1 pack into a single byte as `0x01` (Minor in
  the high nibble, Bug in the low nibble) — high nibble = the
  *first*-declared field.
- **`fill (bit|byte|word|long)[N]`** emits `N` zero-valued units
  (`byte`=8 bits, `word`=16, `long`=32, `bit`=1); confirmed against
  rWindParam1's `fill long[3]` (12 zero bytes sit exactly between
  `wInfoHeight` and `wposition` in the golden bytes).
- **Attribute word**: `locked`=0x8000, `fixed`=0x4000, `preload`=0x0040,
  `nospecialmemory`=0x0008, `Convert`=0x0800 (design doc); a bare numeric
  attribute (e.g. `$8000`) is OR'd in directly. Confirmed against golden
  index attrs: `locked,fixed,preload,nospecialmemory` -> `0xC048`;
  `Convert,locked` (on the 4 `read` statements) -> `0x8800`; a lone `$8000`
  attribute (the "X" icon, `resource rIcon ($07FF0058, $8000)`) -> `0x8000`
  unchanged; no attributes -> `0x0000`.

ReverseBytes (rVersion)
=======================
`ReverseBytes { <fields> }` packs `<fields>` exactly like a bare group,
then **reverses the byte order of the resulting (byte-aligned) buffer**.
Confirmed against rVersion(1)'s `{ 6,0,1,release,$00 }`: forward bit-packing
of (byte Major=6, bitstring[4] Minor=0, bitstring[4] Bug=1, byte
ReleaseStage=release=0xA0, byte NonFinal=0) gives bytes
`06 01 A0 00`; the golden resource's first 4 bytes are `00 A0 01 06` —
exactly that buffer reversed. Any other bare-identifier group (the parser's
general `GroupField`) is treated as a transparent grouping with no
transform (untested by the corpus — only `ReverseBytes` appears — but a
safe, documented default).

Modifiers are generation no-ops
================================
`hex`/`unsigned`/`binary`/`literal`/`decimal`/`octal` (the field modifiers
R4 preserves) never change the bytes this module emits — they are purely
DeRez display-format hints in real Rez. Two's-complement bytes are
identical regardless of signedness, so this costs nothing.

Escape sequences inside `STRING` literal bytes
================================================
The lexer hands `StrLit`/`HexLit` raw, undecoded bytes (per its own
docstring, deferring escape decoding to "a later phase"). Scanning the
Sys.Resources corpus files for backslash sequences that actually appear
inside a `resource`/`read` statement's string values (`work/
rezgencheck.py`'s harness corpus; TypesIIGS.r's own unused `TBStyle*`-style
`\$XX` macros are never invoked by any of Sys.Resources' 138 resources)
turned up three forms there; EasyMount (the M7 follow-on target) confirmed
a fourth (`\$HH`) for real. All four, each confirmed against golden bytes:
    \0xHH   (H = hex digit, case-insensitive)  -> one byte, that hex value
             (e.g. rErrorString's trailing "\0x00" -> one 0x00 byte;
             confirmed the *whole* preceding text is NOT NUL-padded beyond
             this one explicit byte)
    \$HH    (H = hex digit, case-insensitive)  -> one byte, that hex value
             -- EasyMount's Cancel/Connect `rControlTemplate`s pass
             `{"\$1B","\$1B",...}`/`{"\$0D","\$0D",...}` as `KeyEquiv` char
             pairs; golden `/System/System.Setup/EasyMount` bytes at that
             offset are `1b 1b`/`0d 0d` (single ESC/CR bytes), not the 4
             literal characters `$`,`1`,`B` a bare backslash-drop would
             produce. Sys.Resources itself never exercises this form (see
             `decode_string_escapes`'s docstring).
    \n                                          -> one byte, 0x0D (Mac CR,
             *not* 0x0A) — confirmed against rErrorString($07FF0099)'s
             `"...formatted." "\n\n" "800K disks..."`, whose golden bytes
             show `\r\r` (0x0D 0x0D) at exactly that point, and against
             `\0x0D`/`\0x0d` (also 0x0D) used interchangeably elsewhere for
             the identical byte
    \<any other char>                           -> that literal character,
             backslash dropped (a generic fallback for anything not
             matching the three forms above)
High MacRoman bytes (e.g. the "can't" apostrophe rendered as 0xD5) pass
through completely untouched, confirming the lexer's latin-1 round-trip
contract already does the right thing for non-ASCII content.

Field <-> value matching (the heart of the algorithm)
======================================================
A resource's `values` list is matched against its type template's `fields`
list positionally, left to right, via a shared recursive walk
(`_emit_field_list`) used identically for every "compound" field kind:

  - `Label`: consumes no value; records the *current* bit offset under its
    name (for `$$Word`/`$$Byte`/`$$Long`/bare-name label references) and,
    if it immediately precedes a `TypedField`, tags that field's *written
    value* under the same name too (`$$Word(height)` etc. read this back).
  - `TypedField` with a bare `default` and no `named_values` (e.g.
    `integer = $50;`, `longint = $$Countof(NAMES);`,
    `integer = (Mask-Image)/8 - 6;`, `integer = 3+$$optionalcount(Fields);`)
    consumes **zero** values — its default expression is *always* used,
    computed at emission time (see "two-pass generation" below).
  - `TypedField` with `named_values` (e.g. `longint behind=0,infront=-1;`,
    rVersion's `hex byte development=0x20,...,release=0xA0;`) consumes
    **one** value, resolved against its own C-enum-style name table if
    that value is a bare `Name`, or evaluated directly otherwise. Confirmed
    the only 4 bare `Name` value-nodes anywhere in the 138 resources'
    values (`release`, `verUS`, `infront` x2) are all exactly this case —
    *every* other identifier used as a resource value (menu/control flag
    arithmetic like `RefIsResource*MenuTitleRefShift+fAllowCache`) is
    already a plain number by the time the parser sees it, because it was
    a simple object-like `#define` the lexer's preprocessor already
    expanded. So a bare `Name` *value* node is never resolved as a label
    offset — only a `TypedField.default` *expression* is (see rIcon below).
  - A plain `TypedField` (no default, no named_values) consumes exactly
    one value, encoded per its basetype.
  - `ArrayField`/`OptionalField`/`SwitchField`/`GroupField` each consume
    exactly **one** value from their enclosing stream too — a `GroupValue`
    for the first three, a `CaseValue` for `SwitchField` (matched against
    `SwitchField.cases` by name, case-insensitively) — and then walk their
    *own* field list against that one value's *inner* value list
    recursively. `ArrayField` repeats this either a literal `bound` number
    of times, or (`bound is None`) until the inner value list is
    exhausted, one iteration per however many raw values its own
    single-iteration field list needs (confirmed: rMenu's/rControlList's
    unbounded `array { _mybase_ longint; }` — 1 field/iteration — consumes
    the inner group's values one at a time; rControlTemplate's
    `KeyEquiv = array[1]{ char;char;word;word; }` macro — 4
    fields/iteration, `bound`=1 — consumes exactly one 4-element nested
    group).
  - `OptionalField` is the same as `ArrayField` with an implicit
    bound of 0-or-1: if the enclosing stream has no more values at that
    point, it is entirely absent (contributes 0 bytes, `$$optionalCount`
    reads back 0); if present, it need not consume *all* of its declared
    template fields — confirmed against `editLineControl`'s optional
    `Fields` group (6 template fields, but CTLTMP_00000003's resource
    statement supplies only 5 values) producing a resource 8 bytes
    shorter than a 6-value sibling, with the trailing (password-character)
    field entirely omitted, not zero-filled. `$$optionalCount`/
    `$$Countof` both read back exactly "how many top-level values were
    consumed from that named group" — confirmed against every
    `rControlTemplate`'s `pCount = 3 + $$optionalCount(Fields)` (9 for a
    6-value case, 8 for the 5-value `editLineControl` case).

Two-pass generation (why, and what it buys)
============================================
Some `default` expressions reference a **label that appears later in the
field list** — rIcon's `integer = (Mask-Image)/8 - 6;` (labelled `image:`)
subtracts the *bit offset* of the later `mask:` label from its own; the
same field-order-agnostic forward reference happens with
`$$optionalCount`/`$$Countof` of a named group declared later
(`rControlTemplate`'s pCount field precedes its own `switch`). Bare
(non-`$$`-prefixed) label names in an expression evaluate to that label's
*bit offset* from the start of the resource (not its value) — this is what
makes the rIcon formula work: `(offset(mask) - offset(image)) / 8` is
exactly the byte length of everything between the two labels, and `- 6`
removes the 3 fixed 16-bit fields (`image`'s own size field, height,
width) that sit between them, leaving just the image data's own length —
which is never actually *read back* by this generator (the adjacent
`hex string [$$Word(image)]` field's byte count comes from its literal
value's own length, not from evaluating this bracket — see above), but the
`image:`-labelled *field's own stored value* still has to come out right
byte-for-byte, and does.

This module resolves such forward references with two structurally
identical passes over the same field/value tree (`_generate_resource_data`):
a *measure* pass (a `_MeasureWriter` that only tracks bit position, never
evaluating any `TypedField.default` — a defaulted field's width never
depends on its own value, only its basetype, so skipping the value
computation entirely sidesteps the forward reference) that fully populates
every label's bit offset and every named group's consumed-value count; then
an *emit* pass (a real `_BitWriter`) that evaluates every default now that
all forward and backward references are already resolved. Both passes run
the identical field/value-matching logic (`_emit_field_list` and friends),
so which values get consumed by which fields is guaranteed identical
between them — confirmed empirically (`work/rezgencheck.py`) by the fact
that every corpus resource's measured width matches its emitted length.

`$$ArrayIndex`/`Subscript` (best-effort, NOT golden-verified)
===============================================================
`rBundle`/`rFinderPath` (the only templates using `$$ArrayIndex(name)` and
`label[$$ArrayIndex(name)]`-style subscripted label references) are never
instantiated anywhere in the 6.0.1 corpus (`rBundle`'s typeid, $802B, never
appears among the 138 resource statements), so this behavior cannot be
golden-diffed. A reasonable implementation is provided (current iteration
index of the innermost named array a `$$ArrayIndex` call appears inside;
subscripted label offsets recorded per iteration of the innermost enclosing
named array) and pinned by a hand-written test in `tests/test_rez_gen.py`,
but — unlike everything else in this module — it is *not* backed by a
golden-byte comparison and should be treated as speculative.
"""
from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from gsasm.rez import parser


class GenError(Exception):
    """Fatal generation failure. Message is pre-formatted `file:line: ...`
    (or a bare description for the synthesized rResName resource, which has
    no source location)."""


# ==========================================================================
# Attribute word (design doc: "Golden fork format — decoded facts")
# ==========================================================================
ATTR_BITS = {
    'locked': 0x8000,
    'fixed': 0x4000,
    'preload': 0x0040,
    'nospecialmemory': 0x0008,
    'convert': 0x0800,   # only ever seen on `read` statements in this corpus
}


def _compute_attr(attrs, file, line):
    word = 0
    for a in attrs:
        if isinstance(a, parser.Name):
            key = a.name.lower()
            if key not in ATTR_BITS:
                raise GenError(f"{file}:{line}: unknown attribute keyword {a.name!r}")
            word |= ATTR_BITS[key]
        else:
            # A bare numeric attribute (e.g. `$8000`) passes through
            # directly (design doc); OR'd in for robustness in case it's
            # ever combined with keyword attrs (never observed in this
            # corpus, which only ever supplies a lone numeric attr or a
            # keyword-only combination, never both).
            word |= _eval_expr(a, _Ctx()) & 0xFFFF
    return word & 0xFFFF


# ==========================================================================
# rResName synthesis constants (see module docstring)
# ==========================================================================
RESNAME_TYPE = 0x8014
RESNAME_ID = 0x00018001
RESNAME_FORMAT = 1     # observed constant "name holder format" value


# ==========================================================================
# Bit-level writers: the SAME field/value-matching code (_emit_field_list
# and friends) runs against either writer, so pass 1 (measure) and pass 2
# (emit) can never disagree about which fields consume which values --
# only about whether a defaulted field's value expression gets evaluated
# (see _emit_typed_field and the module docstring's "two-pass generation").
# ==========================================================================
class _MeasureWriter:
    """Tracks bit position only; never stores real content. `to_bytes()`
    returns zero bytes of the right length so code paths that need to read
    back a just-written buffer (GroupField/ReverseBytes) work unmodified in
    either writer flavor."""
    measuring = True

    def __init__(self):
        self._pos = 0

    def write_bits(self, value, width):
        if width < 0:
            raise GenError('negative bit width')
        self._pos += width

    def write_bytes(self, data):
        self._pos += 8 * len(data)

    @property
    def bit_pos(self):
        return self._pos

    def to_bytes(self):
        if self._pos % 8:
            raise GenError('resource data not byte-aligned at group boundary')
        return bytes(self._pos // 8)


class _BitWriter:
    """Real bit-level byte accumulator, MSB-first within each byte (see
    module docstring's bitstring-packing evidence)."""
    measuring = False

    def __init__(self):
        self._out = bytearray()
        self._acc = 0
        self._nbits = 0   # pending bits in `_acc`, always in [0, 8)

    def write_bits(self, value, width):
        if width < 0:
            raise GenError('negative bit width')
        if width == 0:
            return
        value &= (1 << width) - 1
        self._acc = (self._acc << width) | value
        self._nbits += width
        while self._nbits >= 8:
            self._nbits -= 8
            self._out.append((self._acc >> self._nbits) & 0xFF)
        self._acc &= (1 << self._nbits) - 1 if self._nbits else 0

    def write_bytes(self, data):
        if self._nbits == 0:
            self._out += data
        else:
            for b in data:
                self.write_bits(b, 8)

    @property
    def bit_pos(self):
        return len(self._out) * 8 + self._nbits

    def to_bytes(self):
        if self._nbits:
            raise GenError('resource data not byte-aligned at end')
        return bytes(self._out)


# ==========================================================================
# Value-stream cursor: positional field<->value matching (see module
# docstring, "Field <-> value matching")
# ==========================================================================
class _Cursor:
    __slots__ = ('values', 'i')

    def __init__(self, values):
        self.values = values
        self.i = 0

    def has_next(self):
        return self.i < len(self.values)

    def next(self, what, file, line):
        if self.i >= len(self.values):
            raise GenError(f"{file}:{line}: ran out of resource values while "
                            f"matching {what}")
        v = self.values[self.i]
        self.i += 1
        return v


# ==========================================================================
# Symbol table threaded through one resource's generation (both passes)
# ==========================================================================
class _Ctx:
    def __init__(self):
        self.offsets = {}          # label name -> bit offset from resource start
        self.counts = {}           # named array/optional group -> consumed count
        self.values = {}           # label name -> written scalar value (backward refs)
        self.array_stack = []      # [(array_name, iter_index), ...], innermost last
        self.indexed_offsets = {}  # (label_name, iter_index) -> bit offset (speculative)


def _mask(width):
    return (1 << width) - 1


def _key(name):
    """Normalize a label/array/optional-group name for symbol-table
    lookup. Confirmed necessary by golden diffing: TypesIIGS.r's `rIcon`
    declares labels `image:`/`mask:` (lowercase) but its own
    `integer = (Mask-Image)/8 - 6;` default references them as
    `Mask`/`Image` (capitalized) in the SAME template -- real Rez clearly
    resolves label references case-insensitively even though the parser's
    own docstring leaves case sensitivity for non-keyword identifiers as
    "a semantic question R5 owns". `$$Word(image)` in the same template
    uses the label's own lowercase spelling, so this can't be "always
    capitalized" or some other fixed convention -- it's genuine
    case-insensitive matching."""
    return name.lower()


# ==========================================================================
# Expression evaluation
# ==========================================================================
def _cdiv(a, b):
    """C-style truncating division (matches how these formulas are always
    used in the corpus: exact division of non-negative byte/bit counts)."""
    q = abs(a) // abs(b)
    return -q if (a < 0) != (b < 0) else q


def _eval_expr(expr, ctx):
    if isinstance(expr, parser.Num):
        return expr.value
    if isinstance(expr, parser.UnaryOp):
        v = _eval_expr(expr.operand, ctx)
        return -v if expr.op == '-' else v
    if isinstance(expr, parser.BinOp):
        left = _eval_expr(expr.left, ctx)
        right = _eval_expr(expr.right, ctx)
        if expr.op == '+':
            return left + right
        if expr.op == '-':
            return left - right
        if expr.op == '*':
            return left * right
        if expr.op == '/':
            if right == 0:
                raise GenError(f"{expr.file}:{expr.line}: division by zero")
            return _cdiv(left, right)
        raise GenError(f"{expr.file}:{expr.line}: unsupported operator {expr.op!r}")
    if isinstance(expr, parser.Name):
        # A bare label reference: the label's BIT OFFSET from the start of
        # the resource (real-Rez semantics; see module docstring's rIcon
        # "(Mask-Image)/8-6" evidence). Only ever reached from a
        # TypedField.default expression in this corpus -- every bare Name
        # appearing as a resource *value* is resolved via named_values
        # instead, before _eval_expr is ever called on it.
        if _key(expr.name) in ctx.offsets:
            return ctx.offsets[_key(expr.name)]
        raise GenError(f"{expr.file}:{expr.line}: unresolved identifier "
                        f"{expr.name!r} (not a known label)")
    if isinstance(expr, parser.Call):
        return _eval_call(expr, ctx)
    if isinstance(expr, parser.Subscript):
        return _eval_subscript(expr, ctx)
    raise GenError(f"cannot evaluate {type(expr).__name__} as an expression")


def _call_name_arg(call):
    if len(call.args) != 1 or not isinstance(call.args[0], parser.Name):
        raise GenError(f"{call.file}:{call.line}: {call.func} expects a single "
                        f"name argument")
    return call.args[0].name


def _eval_call(call, ctx):
    fn = call.func.lower()
    if fn in ('$$word', '$$byte', '$$long'):
        # Read back a PREVIOUSLY WRITTEN field's value (backward reference
        # only -- every corpus usage is backward, e.g. rCursor/rMyCursor's
        # $$Word(height)/$$Word(width) read fields declared earlier in the
        # same template). Not actually needed to reproduce any of the 139
        # golden resources (see module docstring: string/hex-string field
        # lengths come from the literal value's own byte length, not from
        # evaluating their size bracket) but implemented properly for
        # correctness and for tests/test_rez_gen.py's direct unit test.
        label = _call_name_arg(call)
        if _key(label) not in ctx.values:
            raise GenError(f"{call.file}:{call.line}: {call.func}({label}) refers "
                            f"to a field not yet written (forward references are "
                            f"not supported for $$Word/$$Byte/$$Long)")
        return ctx.values[_key(label)]
    if fn == '$$countof':
        name = _call_name_arg(call)
        if _key(name) not in ctx.counts:
            raise GenError(f"{call.file}:{call.line}: $$Countof({name}) refers to "
                            f"an unknown array/optional group")
        return ctx.counts[_key(name)]
    if fn == '$$optionalcount':
        name = _call_name_arg(call)
        if _key(name) not in ctx.counts:
            raise GenError(f"{call.file}:{call.line}: $$optionalCount({name}) "
                            f"refers to an unknown optional/array group")
        return ctx.counts[_key(name)]
    if fn == '$$arrayindex':
        # Best-effort / not golden-verified -- see module docstring.
        name = _call_name_arg(call)
        for aname, idx in reversed(ctx.array_stack):
            if aname == _key(name):
                return idx
        raise GenError(f"{call.file}:{call.line}: $$ArrayIndex({name}) used "
                        f"outside of array {name!r}'s own field list")
    raise GenError(f"{call.file}:{call.line}: unsupported meta-function "
                    f"{call.func!r}")


def _eval_subscript(sub, ctx):
    # Best-effort / not golden-verified -- see module docstring.
    idx = _eval_expr(sub.index, ctx)
    key = (_key(sub.name), idx)
    if key in ctx.indexed_offsets:
        return ctx.indexed_offsets[key]
    raise GenError(f"{sub.file}:{sub.line}: no recorded offset for "
                    f"{sub.name}[{idx}] (subscripted label references are "
                    f"speculative/best-effort -- see gen.py module docstring)")


# ==========================================================================
# Named-value (C-enum-style) resolution
# ==========================================================================
def _resolve_named_value(named_values, val, ctx, file, line):
    # _key()-normalized both sides: real Rez resolves enum-style named
    # values case-insensitively, same as label references (see `_key`'s
    # docstring). Confirmed by the same identifier model that makes
    # `$$Word(Height)` resolve a lowercase `height:` label -- a resource
    # value spelled `Release` must equally match a field's `release=1`
    # named value (Medium/low finding: `type 1 { integer release=1; };
    # resource 1(1) { Release };` used to raise GenError even though
    # `release` is a valid named value).
    table = {}
    nxt = 0
    for nv in named_values:
        if nv.value is not None:
            nxt = _eval_expr(nv.value, ctx)
        table[_key(nv.name)] = nxt
        nxt += 1
    if isinstance(val, parser.Name):
        if _key(val.name) not in table:
            raise GenError(f"{file}:{line}: {val.name!r} is not one of this "
                            f"field's named values ({sorted(table)})")
        return table[_key(val.name)]
    return _eval_expr(val, ctx)


# ==========================================================================
# String/hex-string escape decoding (see module docstring)
# ==========================================================================
_HEXDIGITS = b'0123456789abcdefABCDEF'


def _is_hex_byte(b):
    return b in _HEXDIGITS


def decode_string_escapes(raw: bytes) -> bytes:
    """Decode the backslash escapes this corpus actually uses inside a
    `StrLit`'s raw bytes (see module docstring for the evidence): `\\0xHH`
    (one byte, hex value HH), `\\$HH` (one byte, hex value HH -- see below),
    `\\n` (one byte, 0x0D -- Mac CR, not 0x0A), and `\\<anything else>`
    (that literal byte, backslash dropped).

    `\\$HH`: EasyMount's `EasyMount.rii` (M7 follow-on target) uses this
    form for real, in the `simpleButtonControl`/`radioControl` `KeyEquiv`
    char pairs of its Cancel/Connect buttons: `{"\\$1B", "\\$1B", ...}` and
    `{"\\$0D", "\\$0D", ...}` -- golden-diffed directly against
    `/System/System.Setup/EasyMount`'s resource fork (rControlTemplate
    id=2/3, first differing byte at the KeyEquiv char pair): golden bytes
    are `1b 1b` / `0d 0d`, i.e. single ESC/CR bytes, not the 4 literal
    characters `$`, `1`, `B` the old generic-fallback rule would have
    produced. TypesIIGS.r's own unused `TBStyle*`-style `\\$XX` macro
    comments (never invoked by any Sys.Resources resource) hinted at this
    form without confirming it; EasyMount's golden bytes are the
    confirmation."""
    out = bytearray()
    i, n = 0, len(raw)
    while i < n:
        b = raw[i]
        if b == 0x5C and i + 1 < n:   # backslash
            if (n - i >= 5 and raw[i + 1] == 0x30            # '0'
                    and raw[i + 2] in (0x78, 0x58)            # 'x'/'X'
                    and _is_hex_byte(raw[i + 3]) and _is_hex_byte(raw[i + 4])):
                out.append(int(raw[i + 3:i + 5].decode('ascii'), 16))
                i += 5
                continue
            if (n - i >= 4 and raw[i + 1] == 0x24             # '$'
                    and _is_hex_byte(raw[i + 2]) and _is_hex_byte(raw[i + 3])):
                out.append(int(raw[i + 2:i + 4].decode('ascii'), 16))
                i += 4
                continue
            if raw[i + 1] == 0x6E:   # 'n' -> Mac CR
                out.append(0x0D)
                i += 2
                continue
            out.append(raw[i + 1])
            i += 2
            continue
        out.append(b)
        i += 1
    return bytes(out)


def _value_bytes(val, file, line):
    if isinstance(val, parser.StrLit):
        return decode_string_escapes(val.value)
    if isinstance(val, parser.HexLit):
        return val.value
    raise GenError(f"{file}:{line}: expected a string or hex-string literal, "
                    f"got {type(val).__name__}")


# ==========================================================================
# TypedField width (only needed for the "no resource value consumed"
# defaulted-field case; see module docstring's two-pass-generation note)
# ==========================================================================
_FIXED_WIDTH = {'byte': 8, 'integer': 16, 'word': 16, 'longint': 32, 'char': 8}


def _typed_field_fixed_width(f, ctx):
    bt = f.basetype
    if bt in _FIXED_WIDTH:
        return _FIXED_WIDTH[bt]
    if bt == 'bitstring':
        width = _eval_expr(f.size, ctx) if f.size is not None else 1
        if width < 0:
            raise GenError(f"{f.file}:{f.line}: negative bitstring "
                            f"width ({width})")
        return width
    raise GenError(f"{f.file}:{f.line}: a defaulted (no resource value) field "
                    f"of basetype {bt!r} has no fixed width; not supported")


def _write_int(writer, v, width):
    """Write a byte/integer/longint scalar (8/16/32-bit) as LITTLE-ENDIAN
    bytes -- confirmed against rWindColor's `0b...` binary literals and
    rMenu's longint IDs (see module docstring's endianness evidence).
    `bitstring` fields do NOT go through this: they pack MSB-first at the
    BIT level via `writer.write_bits` directly, a genuinely different
    concern from a multi-byte scalar's byte order (confirmed separately
    via rVersion's `ReverseBytes` nibble packing) -- conflating the two
    was an early bug caught by work/rezgencheck.py (every multi-byte field
    came out byte-swapped)."""
    v &= _mask(width)
    if width == 8:
        writer.write_bits(v, 8)
    else:
        writer.write_bytes(v.to_bytes(width // 8, 'little'))


def _group_ints(val, n, ctx, file, line):
    if not isinstance(val, parser.GroupValue):
        raise GenError(f"{file}:{line}: expected a brace-enclosed {n}-element "
                        f"group, got {type(val).__name__}")
    if len(val.values) != n:
        raise GenError(f"{file}:{line}: expected {n} elements, got "
                        f"{len(val.values)}")
    return [_eval_expr(e, ctx) for e in val.values]


def _write_string_like(f, data, writer):
    bt = f.basetype
    if bt == 'string':
        writer.write_bytes(data)
    elif bt == 'pstring':
        if len(data) > 255:
            raise GenError(f"{f.file}:{f.line}: pstring content exceeds 255 "
                            f"bytes ({len(data)})")
        writer.write_bytes(bytes([len(data)]))
        writer.write_bytes(data)
        if f.size is not None:
            # Fixed-size pstring[N] -- NOT exercised by the corpus (every
            # pstring field here is unbounded); best-effort: N is the
            # field's total byte size (length byte + content), zero-padded.
            total = _eval_expr(f.size, _Ctx())
            used = 1 + len(data)
            if used > total:
                raise GenError(f"{f.file}:{f.line}: pstring[{total}] too "
                                f"small for a {used}-byte pstring")
            writer.write_bits(0, (total - used) * 8)
    elif bt == 'cstring':
        # NOT exercised by the corpus; best-effort per design-doc field
        # inventory: raw bytes + one NUL terminator.
        writer.write_bytes(data)
        writer.write_bytes(b'\x00')
    elif bt == 'wstring':
        # NOT exercised by the corpus; best-effort: 2-byte LE length prefix
        # (consistent with every other multi-byte field's endianness).
        if len(data) > 0xFFFF:
            raise GenError(f"{f.file}:{f.line}: wstring content exceeds 65535 "
                            f"bytes ({len(data)})")
        writer.write_bytes(struct.pack('<H', len(data)))
        writer.write_bytes(data)
    else:
        raise GenError(f"{f.file}:{f.line}: not a string-like basetype: {bt!r}")


def _write_field_value(f, val, ctx, writer):
    """Encode ONE already-matched Value node for TypedField `f`, writing it
    to `writer`. Returns the scalar int value written (for $$Word/$$Byte/
    $$Long label lookups), or None for non-scalar basetypes."""
    bt = f.basetype
    if bt in ('byte', 'integer', 'word', 'longint', 'bitstring'):
        if f.named_values:
            v = _resolve_named_value(f.named_values, val, ctx, f.file, f.line)
        else:
            if isinstance(val, (parser.StrLit, parser.HexLit, parser.GroupValue,
                                 parser.CaseValue)):
                raise GenError(f"{f.file}:{f.line}: expected a numeric "
                                f"expression for a {bt} field, got "
                                f"{type(val).__name__}")
            v = _eval_expr(val, ctx)
        if bt == 'bitstring':
            width = _eval_expr(f.size, ctx) if f.size is not None else 1
            if width < 0:
                raise GenError(f"{f.file}:{f.line}: negative bitstring "
                                f"width ({width})")
            writer.write_bits(v & _mask(width), width)
        else:
            _write_int(writer, v, _FIXED_WIDTH[bt])
        return v
    if bt == 'char':
        if isinstance(val, parser.StrLit):
            data = decode_string_escapes(val.value)
            v = data[0] if data else 0
        elif isinstance(val, parser.HexLit):
            v = val.value[0] if val.value else 0
        else:
            v = _eval_expr(val, ctx) & 0xFF
        writer.write_bits(v & 0xFF, 8)
        return v
    if bt in ('string', 'pstring', 'cstring', 'wstring'):
        data = _value_bytes(val, f.file, f.line)
        _write_string_like(f, data, writer)
        return None
    if bt == 'point':
        for v in _group_ints(val, 2, ctx, f.file, f.line):
            _write_int(writer, v, 16)
        return None
    if bt == 'rect':
        for v in _group_ints(val, 4, ctx, f.file, f.line):
            _write_int(writer, v, 16)
        return None
    if bt == 'boolean':
        # NOT exercised by the corpus; best-effort: 1 byte, 0 or 1.
        if isinstance(val, parser.StrLit):
            v = 1 if val.value else 0
        else:
            v = 1 if _eval_expr(val, ctx) else 0
        writer.write_bits(v, 8)
        return v
    raise GenError(f"{f.file}:{f.line}: unsupported basetype {bt!r}")


def _emit_typed_field(f, cursor, ctx, writer):
    if f.default is not None and not f.named_values:
        # Fixed/computed constant: NEVER consumes a resource value. Its
        # width never depends on its value, so the measure pass can skip
        # evaluating it entirely -- this is what makes forward-referencing
        # defaults (rIcon's "(Mask-Image)/8-6", rControlTemplate's
        # "3+$$optionalCount(Fields)") resolvable at all: by the time the
        # EMIT pass reaches this field, pass 1 has already fully populated
        # every label offset and named-group count in the whole template.
        width = _typed_field_fixed_width(f, ctx)
        if writer.measuring:
            writer.write_bits(0, width)
            return None
        v = _eval_expr(f.default, ctx)
        if f.basetype == 'bitstring':
            writer.write_bits(v & _mask(width), width)
        else:
            _write_int(writer, v, width)
        return v
    val = cursor.next(f"a {f.basetype} field", f.file, f.line)
    return _write_field_value(f, val, ctx, writer)


def _emit_array_field(f, cursor, ctx, writer):
    outer = cursor.next(f"array {f.name or ''!r}", f.file, f.line)
    if not isinstance(outer, parser.GroupValue):
        raise GenError(f"{f.file}:{f.line}: array expected a brace-enclosed "
                        f"value, got {type(outer).__name__}")
    inner = _Cursor(outer.values)
    count = 0
    if f.bound is not None:
        n = _eval_expr(f.bound, ctx)
        if n < 0:
            raise GenError(f"{f.file}:{f.line}: negative array bound ({n})")
        for idx in range(n):
            if f.name:
                ctx.array_stack.append((_key(f.name), idx))
            _emit_field_list(f.fields, inner, ctx, writer)
            if f.name:
                ctx.array_stack.pop()
            count += 1
    else:
        idx = 0
        while inner.has_next():
            before = inner.i
            if f.name:
                ctx.array_stack.append((_key(f.name), idx))
            _emit_field_list(f.fields, inner, ctx, writer)
            if f.name:
                ctx.array_stack.pop()
            if inner.i == before:
                raise GenError(f"{f.file}:{f.line}: array iteration made no "
                                f"progress consuming values (empty field list?)")
            count += 1
            idx += 1
    # A bounded array's fixed iteration count can finish without draining
    # `inner` (e.g. `array[2]{ integer; }` given `{1,2,3}` -- only 2 of the
    # 3 supplied values get consumed); this is a MANDATORY field list (see
    # module docstring / `_emit_field_list`'s `allow_partial`), so leftover
    # values here are a bug in the source, not legitimate partial fill --
    # raise rather than silently dropping the trailing value(s) (High
    # finding: `type 1 { array [2] { integer; }; integer; };
    # resource 1(1) { { 1, 2, 3 }, 9 };` used to silently drop the `3`).
    if inner.i != len(inner.values):
        raise GenError(f"{f.file}:{f.line}: {len(inner.values) - inner.i} "
                        f"unconsumed value(s) left over in array "
                        f"{f.name or ''!r}")
    if f.name:
        ctx.counts[_key(f.name)] = count


def _emit_optional_field(f, cursor, ctx, writer):
    if cursor.has_next():
        val = cursor.next(f"optional group {f.name!r}", f.file, f.line)
        if not isinstance(val, parser.GroupValue):
            raise GenError(f"{f.file}:{f.line}: optional group {f.name!r} "
                            f"expected a brace-enclosed value, got "
                            f"{type(val).__name__}")
        inner = _Cursor(val.values)
        # THE one place partial fill is legitimate (see module docstring
        # and `_emit_field_list`'s `allow_partial` parameter): an `optional`
        # group's own resource value may supply fewer values than its
        # template declares fields for (editLineControl's trailing
        # passwordChar field; EasyMount's iconButtonControl KeyEquiv array).
        _emit_field_list(f.fields, inner, ctx, writer, allow_partial=True)
        count = inner.i
        if inner.i != len(inner.values):
            raise GenError(f"{f.file}:{f.line}: {len(inner.values) - inner.i} "
                            f"unconsumed value(s) left over in optional "
                            f"group {f.name!r}")
    else:
        count = 0
    ctx.counts[_key(f.name)] = count


def _emit_switch_field(f, cursor, ctx, writer):
    val = cursor.next('a switch case value', f.file, f.line)
    if not isinstance(val, parser.CaseValue):
        raise GenError(f"{f.file}:{f.line}: switch expected a `name{{...}}` "
                        f"case value, got {type(val).__name__}")
    case = None
    for c in f.cases:
        if c.name.lower() == val.name.lower():
            case = c
            break
    if case is None:
        raise GenError(f"{f.file}:{f.line}: unknown switch case {val.name!r} "
                        f"(known: {[c.name for c in f.cases]})")
    inner = _Cursor(val.values)
    _emit_field_list(case.fields, inner, ctx, writer)
    if inner.i != len(inner.values):
        raise GenError(f"{f.file}:{f.line}: {len(inner.values) - inner.i} "
                        f"unconsumed value(s) left over in switch case "
                        f"{val.name!r}")


def _emit_group_field(f, cursor, ctx, writer):
    val = cursor.next(f"group {f.keyword!r}", f.file, f.line)
    if not isinstance(val, parser.GroupValue):
        raise GenError(f"{f.file}:{f.line}: group {f.keyword!r} expected a "
                        f"brace-enclosed value, got {type(val).__name__}")
    inner = _Cursor(val.values)
    sub_writer = writer.__class__()
    _emit_field_list(f.fields, inner, ctx, sub_writer)
    if inner.i != len(inner.values):
        raise GenError(f"{f.file}:{f.line}: {len(inner.values) - inner.i} "
                        f"unconsumed value(s) left over in group "
                        f"{f.keyword!r}")
    data = sub_writer.to_bytes()
    if f.keyword.lower() == 'reversebytes':
        data = data[::-1]
    writer.write_bytes(data)


_UNIT_BITS = {'bit': 1, 'byte': 8, 'word': 16, 'long': 32}


def _emit_fill_field(f, ctx, writer):
    n = 1 if f.count is None else _eval_expr(f.count, ctx)
    if n < 0:
        raise GenError(f"{f.file}:{f.line}: negative fill count ({n})")
    writer.write_bits(0, n * _UNIT_BITS[f.unit])


def _emit_align_field(f, writer):
    # NOT exercised by the corpus; best-effort per design-doc field
    # inventory.
    unit_bits = _UNIT_BITS[f.unit]
    rem = writer.bit_pos % unit_bits
    if rem:
        writer.write_bits(0, unit_bits - rem)


def _emit_field_list(fields, cursor, ctx, writer, allow_partial=False):
    """Walk `fields` against `cursor`'s value stream (see module docstring,
    "Field <-> value matching"). Shared by the top-level resource body and
    every nested group (array iteration/optional group/switch case/bare
    group).

    `allow_partial`: when True, running out of `cursor` values partway
    through `fields` stops emission of the remainder of this field list
    instead of raising -- the ONE legitimate "partial fill" case, an
    `optional` group's own field list (see `_emit_optional_field`, which is
    the only caller that ever passes `allow_partial=True`). Confirmed
    against `editLineControl`'s `optional Fields` (6 template fields:
    flags/moreFlags/refcon/maxSize/textResID/passwordChar) versus
    CTLTMP_00000003's resource statement, which supplies only 5 values --
    the golden bytes are exactly 8 bytes shorter than a 6-value sibling
    control template, with the trailing passwordChar field entirely
    OMITTED (not zero-filled); and against EasyMount's CTLTMP_00000008
    (`iconButtonControl`'s `optional Fields` -- 8 template fields ending
    in the unnamed `KeyEquiv` array macro, `#define KeyEquiv array[1]{
    char;char;word;word; }`) supplying only 7 resource values: golden size
    is exactly 40 bytes (2 pCount + 4 ID + 8 rect + 4 key procRef + 22 for
    the 7 supplied Fields values), i.e. KeyEquiv is entirely omitted, not
    zero-filled.

    Every OTHER field list -- the top-level resource body, a bounded
    array's per-iteration field list, a switch case's field list, a bare
    group's field list -- is MANDATORY: `allow_partial` defaults to False,
    so running out of values here falls through to the normal
    `cursor.next()`/`_emit_*_field()` call, which raises `GenError` with
    the field's own source location (High finding: `type 1 { integer;
    integer; }; resource 1(1) { 7 };` used to silently emit only one
    integer instead of raising)."""
    pending_label = None
    for item in fields:
        if isinstance(item, parser.Label):
            pos = writer.bit_pos
            ctx.offsets[_key(item.name)] = pos
            if ctx.array_stack:
                _, idx = ctx.array_stack[-1]
                ctx.indexed_offsets[(_key(item.name), idx)] = pos
            pending_label = _key(item.name)
            continue
        if isinstance(item, parser.TypedField):
            needs_value = not (item.default is not None and not item.named_values)
            if needs_value and allow_partial and not cursor.has_next():
                break
            v = _emit_typed_field(item, cursor, ctx, writer)
            if pending_label is not None and v is not None:
                ctx.values[pending_label] = v
            pending_label = None
            continue
        pending_label = None
        if isinstance(item, (parser.ArrayField, parser.SwitchField,
                              parser.GroupField)):
            # Same partial-fill rule as the TypedField case just above:
            # each of these three unconditionally consumes exactly one
            # value node (a GroupValue/CaseValue) from `cursor` before
            # recursing into its own nested field list, so an `optional`
            # group's field list can equally run out right at a nested
            # ArrayField/SwitchField/GroupField instead of at a plain
            # TypedField (confirmed by EasyMount's iconButtonControl case
            # above, whose omitted trailing field IS an ArrayField).
            # NOTE: `OptionalField` is deliberately EXCLUDED from this
            # tuple -- unlike these three, it has its own legitimate
            # "absent" semantics (0-or-1 occurrence, `_emit_optional_field`
            # already handles an exhausted cursor by recording a 0 count
            # and returning, without stopping the rest of the enclosing
            # field list) that must still run so `$$optionalCount`/
            # `$$Countof` resolve; folding it into this same break would
            # wrongly skip that bookkeeping (caught by
            # tests/test_rez_gen.py::test_optional_absent_yields_zero_count).
            if allow_partial and not cursor.has_next():
                break
            if isinstance(item, parser.ArrayField):
                _emit_array_field(item, cursor, ctx, writer)
            elif isinstance(item, parser.SwitchField):
                _emit_switch_field(item, cursor, ctx, writer)
            else:
                _emit_group_field(item, cursor, ctx, writer)
            continue
        if isinstance(item, parser.OptionalField):
            _emit_optional_field(item, cursor, ctx, writer)
        elif isinstance(item, parser.FillField):
            _emit_fill_field(item, ctx, writer)
        elif isinstance(item, parser.AlignField):
            _emit_align_field(item, writer)
        else:
            raise GenError(f"unhandled field kind {type(item).__name__}")


def _generate_resource_data(tmpl, values, file, line):
    ctx = _Ctx()

    # Pass 1: measure. Populates ctx.offsets / ctx.counts fully (including
    # any forward references), never evaluates a defaulted field's value.
    m = _MeasureWriter()
    _emit_field_list(tmpl.fields, _Cursor(values), ctx, m)

    # Pass 2: emit. ctx.offsets/counts carry over (now complete); values/
    # array_stack reset (pass 2 rebuilds them fresh as it goes).
    ctx.values = {}
    ctx.array_stack = []
    bw = _BitWriter()
    cursor = _Cursor(values)
    _emit_field_list(tmpl.fields, cursor, ctx, bw)
    if cursor.i != len(values):
        raise GenError(f"{file}:{line}: {len(values) - cursor.i} unconsumed "
                        f"resource value(s) left over after matching against "
                        f"the type template")
    return bw.to_bytes()


# ==========================================================================
# rResName synthesis
# ==========================================================================
def _build_resname_data(names: List[Tuple[int, bytes]]) -> bytes:
    bw = _BitWriter()
    _write_int(bw, RESNAME_FORMAT, 16)
    _write_int(bw, len(names), 32)
    for rid, name in names:
        _write_int(bw, rid, 32)
        decoded = decode_string_escapes(name)
        if len(decoded) > 255:
            raise GenError(f'rResName entry name too long (>255 bytes): {decoded!r}')
        bw.write_bytes(bytes([len(decoded)]))
        bw.write_bytes(decoded)
    return bw.to_bytes()


# ==========================================================================
# Public API
# ==========================================================================
@dataclass
class GenEntry:
    """One entry per `ResourceStmt`/`ReadStmt` (plus the synthesized
    rResName), in the final source order `emit_fork` wants. See module
    docstring's "Public API" section for field meanings."""
    kind: str                  # 'resource' | 'read' | 'resname'
    file: str
    line: int
    rtype: int
    rid: int
    attr: int
    name: Optional[bytes]
    data: Optional[bytes]


def generate(statements) -> List[GenEntry]:
    """Evaluate every `ResourceStmt` in `statements` against its type
    template, computing its attribute word, and return an ordered
    `list[GenEntry]` — see the module docstring's "Public API" section for
    the exact contract (source order, `read` placeholders, the synthesized
    rResName appended last)."""
    type_table = {}
    for s in statements:
        if isinstance(s, parser.TypeDecl):
            # Last declaration for a given typeid wins (see module
            # docstring: rCursor/rMyCursor redeclaration).
            type_table[s.typeid] = s

    entries: List[GenEntry] = []
    names: List[Tuple[int, bytes]] = []
    for s in statements:
        if isinstance(s, parser.TypeDecl):
            continue

        # Reject nonnumeric resource type IDs here rather than letting them
        # ride through to `emit.emit_fork()`, which assumes every rtype is
        # numeric and masks it with `& 0xFFFF` -- a `str` there is a raw
        # `TypeError`, not a `gsrez:`-prefixed error (Medium/low finding:
        # `type Foo { byte; }; resource Foo(1) { 7 };`). String type IDs
        # already resolve fine internally (`type_table` is keyed by
        # whatever `s.typeid` is, matching `type Foo` to `resource Foo`
        # positionally by name); it's only the *emitted* fork's 16-bit
        # numeric type-index field that can't represent one. There's no
        # name->numeric-ID registry anywhere in this pipeline to fall back
        # on, so rejecting is the only sound option here (the recommended
        # fix's other option).
        if not isinstance(s.typeid, int):
            raise GenError(f"{s.file}:{s.line}: resource type {s.typeid!r} "
                            f"is not a numeric identifier (non-numeric type "
                            f"IDs cannot be emitted; the resource fork's "
                            f"index requires a 16-bit numeric type)")
        if not (0 <= s.typeid <= 0xFFFF):
            raise GenError(f"{s.file}:{s.line}: resource type {s.typeid:#x} "
                            f"out of range (must fit in the fork's 16-bit "
                            f"type-index field, 0..0xFFFF)")

        rid = _eval_expr(s.id, _Ctx())
        if not (0 <= rid <= 0xFFFFFFFF):
            raise GenError(f"{s.file}:{s.line}: resource id {rid:#x} out of "
                            f"range (must fit in the fork's 32-bit id "
                            f"field, 0..0xFFFFFFFF)")
        attr = _compute_attr(s.attrs, s.file, s.line)

        if isinstance(s, parser.ReadStmt):
            entries.append(GenEntry('read', s.file, s.line, s.typeid, rid,
                                     attr, s.name, None))
            continue

        # ResourceStmt
        tmpl = type_table.get(s.typeid)
        if tmpl is None:
            raise GenError(f"{s.file}:{s.line}: no type template declared "
                            f"for resource type {s.typeid!r}")
        data = _generate_resource_data(tmpl, s.values, s.file, s.line)
        entries.append(GenEntry('resource', s.file, s.line, s.typeid, rid,
                                 attr, s.name, data))
        if s.name is not None:
            names.append((rid, s.name))

    if names:
        data = _build_resname_data(names)
        entries.append(GenEntry('resname', '<synthesized>', 0, RESNAME_TYPE,
                                 RESNAME_ID, 0, None, data))

    # Uniqueness over ALL final entries (including the synthesized
    # rResName): RezIIgs resource lookup is keyed on (type, id), so a
    # duplicate key means at least one of the two can never be looked up.
    # Every rtype/rid above has already been range-validated (0..0xFFFF /
    # 0..0xFFFFFFFF), so no further normalization is needed here -- there
    # is no unmasked/masked pair of distinct source values that could
    # collide only after `emit.emit_fork()`'s own `& 0xFFFF` truncation
    # (that truncation is now unreachable for any entry that got this far).
    # Medium/low finding: `resource 1(1) { 1 }; resource 1(1) { 2 };`, and
    # any explicitly-named resource whose id collides with the synthesized
    # rResName's `($8014, $00018001)` key.
    seen = {}
    for e in entries:
        key = (e.rtype, e.rid)
        if key in seen:
            other_file, other_line = seen[key]
            raise GenError(f"{e.file}:{e.line}: duplicate resource key "
                            f"(type {e.rtype:#06x}, id {e.rid:#x}), also "
                            f"defined at {other_file}:{other_line}")
        seen[key] = (e.file, e.line)

    return entries


def to_emit_tuples(entries: List[GenEntry],
                    read_data: Optional[Dict[Tuple[int, int], bytes]] = None):
    """Resolve a `generate()` entry list into the plain
    `list[(rtype, rid, attr, data)]` `gsasm.rez.emit.emit_fork` expects, in
    the same (source, then synthesized rResName last) order.

    `read_data`: `{(rtype, rid): bytes}` supplying the Convert-transformed
    bytes for every `kind == 'read'` entry (the R6 packet's job — this
    module never generates `read` data itself). Every `read` entry must
    have a matching key or `GenError` is raised.
    """
    read_data = read_data or {}
    out = []
    for e in entries:
        if e.kind == 'read':
            key = (e.rtype, e.rid)
            if key not in read_data:
                raise GenError(f"{e.file}:{e.line}: no read/Convert data "
                                f"supplied for read resource "
                                f"({e.rtype:#06x}, {e.rid:#x})")
            data = read_data[key]
        else:
            data = e.data
        out.append((e.rtype, e.rid, e.attr, data))
    return out
