#!/usr/bin/env python3
"""jumptable_probe.py — the ExpressLoad ``~JumpTable`` segment format, decoded.

RESULTS.md / TODO.md §2 long listed the ``~JumpTable`` segments in Tool015/016/018
as "generated by the MPW linker, not present in any source" and proposed reversing
them by driving the linker binary in the SheepShaver image. That is unnecessary:
the format is fully specified by the GS/OS System Loader source already in the
tree (``GS.OS/Loader/Jump.a`` + ``Loader.Equates``) and reproduces every golden
``~JumpTable`` byte-exact.

Format (OMF segment KIND = 0x02 = ``Jump_Segment``):

    header   : 8 bytes of 0x00                    (Loader.Equates seg_jmp_start = 8)
    entries  : jmp_entry_size = 14 bytes each:
                 JE_UserID  (2) = 0x0000          patched to the real UserID at load
                 JE_FileNum (2) = 1               this load file
                 JE_SegNum  (2) = target segment number (1-based, load-file order)
                 JE_Offset  (4) = routine offset within that segment
                 JE_jsl     (4) = 22 00 00 00     $22 = JSL; addr patched to JumpLoad
    trailer  : 4 bytes of 0x00                    (end-of-table marker)

    total = 8 + 14*N + 4

A jump-table entry is emitted for each referenced routine in a **dynamic**
segment (KIND & 0x8000). A caller's far pointer to such a routine is relocated to
``~JumpTable + (seg_jmp_start + entry_index*jmp_entry_size + JE_jsl)`` — i.e. the
entry's JSL, so calling it traps into the Loader, which loads the segment on
demand, patches the JSL to a JML at the real address, and falls through. (See
``Jump.a``: ``JumpLoad`` recovers UserID/FileNum/SegNum/Offset from the bytes
*before* the return address, loads/relocates the segment, then writes ``$5C`` +
the resolved address over ``JE_jsl``.) References to **static** segments do not
use the jump table — they are direct (c)INTERSEG relocations.

This script (a) round-trips the codec against all three golden ~JumpTables and
(b) derives Tool016's from scratch (its only dynamic segment is Pics = seg 5,
referenced at offset 0), proving the entries — not just the framing — are
derivable. Integrating generation into the multi-segment ExpressLoad build
(gsasm/expressload.py + linkiigs segmentation) is the remaining work; the entry
*order* for multi-entry tools (Tool018) must come from the link's reference scan.

    python3 work/jumptable_probe.py
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from gsasm import omf

SEG_JMP_START = 8      # Loader.Equates seg_jmp_start
JMP_ENTRY_SIZE = 14    # Loader.Equates jmp_entry_size
JE_JSL = 10            # Loader.Equates JE_jsl (offset within an entry)


def encode_jumptable(entries, file_num=1):
    """Encode [(seg_num, offset), ...] as the ~JumpTable LCONST image."""
    out = bytearray(b'\x00' * SEG_JMP_START)          # header
    for seg_num, offset in entries:
        out += struct.pack('<HHHI', 0, file_num, seg_num, offset)  # UserID,File,Seg,Off
        out += b'\x22\x00\x00\x00'                    # JSL opcode + unpatched address
    out += b'\x00\x00\x00\x00'                        # trailer
    return bytes(out)


def decode_jumptable(code):
    """Decode a ~JumpTable LCONST image to [(seg_num, offset), ...]."""
    entries = []
    i = SEG_JMP_START
    while i + JMP_ENTRY_SIZE <= len(code):
        uid, fn, sn, off = struct.unpack_from('<HHHI', code, i)
        jsl = code[i + JE_JSL:i + JMP_ENTRY_SIZE]
        if jsl[0] != 0x22:            # not an entry (hit the trailer)
            break
        entries.append((sn, off))
        i += JMP_ENTRY_SIZE
    return entries


def _gold_jumptable(tool):
    for cand in (f'ref/GSOS_6/tool_bin/Tool{tool}#BA0000',
                 f'ref/GSOS_6/tool_bin/Tool{tool}'):
        if os.path.exists(cand):
            raw = open(cand, 'rb').read()
            break
    else:
        return None
    off = 0
    while off < len(raw):
        h = omf.parse_header(raw[off:])
        bc = h['BYTECNT']
        if bc == 0:
            break
        nm = h['SEGNAME'].decode('mac_roman', 'replace').strip().rstrip('\x00')
        if nm == '~JumpTable':
            recs, _ = omf.parse_records(raw[off:off + bc], h['DISPDATA'],
                                        h.get('NUMLEN', 4), h.get('LABLEN', 0))
            return b''.join(r[2] for r in recs if r[1] in ('CONST', 'LCONST'))
        off += bc
    return None


def main():
    npass = nfail = 0
    for tool in ('015', '016', '018'):
        gold = _gold_jumptable(tool)
        if gold is None:
            print(f'Tool{tool}: no ~JumpTable')
            continue
        entries = decode_jumptable(gold)
        rt = encode_jumptable(entries)
        ok = rt == gold
        print(f'Tool{tool}: {len(entries):2d} entr{"y" if len(entries)==1 else "ies"}  '
              f'round-trip {"OK" if ok else "MISMATCH"}')
        npass += ok
        nfail += not ok
        if not ok:
            print('  gold:', gold.hex())
            print('  ours:', rt.hex())

    # Derive Tool016 from scratch: its one dynamic segment is Pics (segment 5 in
    # load-file order ~ExpressLoad=1, main=2, StatText=3, ~JumpTable=4, Pics=5),
    # referenced at offset 0 (PicProc). No decode of the golden entries.
    derived = encode_jumptable([(5, 0)])
    gold16 = _gold_jumptable('016')
    ok = derived == gold16
    print(f"\nTool016 ~JumpTable derived from scratch [(seg=5 Pics, off=0)]: "
          f"{'BYTE-EXACT' if ok else 'MISMATCH'}")
    npass += ok
    nfail += not ok
    if not ok:
        print('  gold:   ', gold16.hex())
        print('  derived:', derived.hex())

    print(f"\nJUMPTABLE_FORMAT {npass} ok / {nfail} bad")
    return 1 if nfail else 0


if __name__ == '__main__':
    sys.exit(main())
